kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80     # Maps HTTP traffic from the host machine to the cluster
        hostPort: 80
        protocol: TCP
      - containerPort: 443    # Maps HTTPS traffic from the host machine to the cluster
        hostPort: 443
        protocol: TCP
      - containerPort: 30090  # Maps traffic to the Prometheus server within the cluster
        hostPort: 30090
        protocol: TCP
      
