apiVersion: apps/v1
kind: Deployment
metadata:
  name: beeapi
  labels:
    app: beeapi
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: beeapi
  template:
    metadata:
      labels:
        app: beeapi
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      containers:
      - name: beeapi
        image: "{{ .Values.beeapi.image.repository }}:{{ .Values.beeapi.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: beeapi-config
        # readinessProbe:
        #   httpGet:
        #     path: /readyz
        #     port: 5000
        #   initialDelaySeconds: 100
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        #   failureThreshold: 3
        #   successThreshold: 1
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"