apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    app: memcached
spec:
  ports:
    - port: {{ .Values.memcached.service.port }}
      targetPort: 11211
  selector:
    app: memcached
  type: ClusterIP
