name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.14'  # specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Run pylint
        run: |
          pylint --disable=C0301 **/*.py

  build:

    runs-on: ubuntu-latest
    needs: lint

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag beeapi:latest
        docker save beeapi:latest -o beeapi_latest.tar
    
    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v4
      with:
        name: beeapi-image
        path: beeapi_latest.tar

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: beeapi-image
          path: .

      - name: Load Docker image
        run: |
          docker load -i beeapi_latest.tar

      - name: Run container and execute tests
        run: |
          docker run -e .env --name test-container -d beeapi:latest
          docker exec test-container pytest

      - name: Cleanup
        run: |
          docker stop test-container
          docker rm test-container
      
  scans:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.14' 

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep --config auto .
      
      - name: Terrascan IaC scanner
        uses: tenable/terrascan-action@v1.4.1
        with:
          iac_type: k8s
      
    
    

            
